// Package worker uploads the generated Worker that serves a domain's MTA-STS
// policy, and binds it to mta-sts.<domain>.
package worker

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
)

// CompatibilityDate pins the Workers runtime behaviour for the generated
// script. It is a constant so that redeploying an unchanged policy produces
// byte-identical source and therefore no diff.
const CompatibilityDate = "2025-01-01"

// maxScriptNameLength is Cloudflare's limit on a Worker script name.
const maxScriptNameLength = 63

// ScriptName is the Worker script name for a domain. Dots are not allowed in a
// script name, so they become hyphens; that alone is not injective (my.site.com
// and my-site.com would collide), so a hash of the original domain is
// appended. It also validates the result against Cloudflare's constraints,
// since the caller cannot recover from a rejected name any other way.
func ScriptName(domain string) (string, error) {
	sum := sha256.Sum256([]byte(domain))
	suffix := hex.EncodeToString(sum[:])[:8]
	name := "mailctl-mta-sts-" + strings.ReplaceAll(domain, ".", "-") + "-" + suffix

	if len(name) > maxScriptNameLength {
		return "", fmt.Errorf(
			"domain %s: Worker script name %q is %d characters, over Cloudflare's %d-character limit",
			domain, name, len(name), maxScriptNameLength)
	}
	for _, r := range name {
		if r > 127 {
			return "", fmt.Errorf(
				"domain %s: Worker script name %q contains a non-ASCII character, which Cloudflare rejects",
				domain, name)
		}
	}
	return name, nil
}

// PolicyScript renders an ES module Worker serving the policy at the
// well-known path and 404ing everything else.
func PolicyScript(policy string) string {
	return `// Generated by mailctl. Do not edit; edit the mailctl config instead.
const POLICY = ` + "`" + escapeTemplate(policy) + "`" + `;

export default {
  async fetch(request) {
    const url = new URL(request.url);
    if (url.pathname !== "/.well-known/mta-sts.txt") {
      return new Response("Not Found", { status: 404 });
    }
    return new Response(POLICY, {
      headers: {
        "content-type": "text/plain; charset=utf-8",
        "cache-control": "public, max-age=3600",
      },
    });
  },
};
`
}

// escapeTemplate makes a string safe inside a JavaScript template literal.
// A policy is generated from config, but config is user input, and a stray
// backtick or ${ would otherwise produce a Worker that fails to compile.
func escapeTemplate(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, "`", "\\`")
	s = strings.ReplaceAll(s, "${", "\\${")
	return s
}
